project:
  type: website
  output-dir: _site
  execute-dir: project

  render:
    - index.ipynb
    - microscopes/index.qmd
    - microscopes/laser_power/*.qmd
    - microscopes/psf/*.qmd
    - microscopes/chromatic_aberration/*.qmd
    - image_analysis/*.qmd
    - image_analysis/fiji_imagej/*.qmd

  resources:
    - "outputs/**"
    - "images/**"

metadata-files:
  - _navbar.yml

website:
  title: "Microscopy and Advanced BioImaging CoRE"

  page-footer:
    center: "Generated automatically with Quarto and GitHub Actions"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

    grid:
      body-width: 750px
      margin-width: 400px
execute:
  echo: false
  warning: false
  error: false
